os:
  - linux

dist: trusty
env:
  global:
    - HOST=x86_64-unknown-linux-gnu
    - CARGO_INCREMENTAL=0

sudo: required
language: rust
rust:
  - stable
  - beta

addons:
  apt:
    packages:
      - build-essential
      - gfortran
      - libopenblas-dev
      - liblapack-dev
      - libssl-dev
  homebrew:
    packages:
      - gcc@9

install:
  # Modified from https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/use-conda-with-travis-ci.html
  - sudo apt-get update
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  - conda config --add channels defaults
  - conda config --add channels bioconda
  - conda config --add channels conda-forge
  - conda install bwa samtools minimap2 prodigal

cache: cargo

before_cache:
  - rm -rf "$TRAVIS_HOME/.cargo/registry/src"
  - if [[ "$TRAVIS_RUST_VERSION" == stable ]]; then cargo install cargo-tarpaulin; fi

script:
  - if [ "$TRAVIS_OS_NAME" = 'osx' ]; then export CC=gcc-9 FC=gfortran-9 LIBRARY_PATH=/usr/local/opt/gcc/lib/gcc/9; fi
  - cargo clean
  - cargo build
  - cargo test

after_success: |
  if [[ "$TRAVIS_RUST_VERSION" == stable ]]; then
    # Uncomment the following line for coveralls.io
    # cargo tarpaulin --ciserver travis-ci --coveralls $TRAVIS_JOB_ID

   Uncomment the following two lines create and upload a report for codecov.io
   cargo tarpaulin --out Xml
   CODECOV_TOKEN="0a2d25a8-b6c0-43c5-a3c4-6f5b0bb8a4d4"
   bash <(curl -s https://codecov.io/bash)
  fi