name: Build manual pages and deploy documentation

on:
  push:
    branches:
      - master
    paths:
      - 'docs/**'
      - 'src/cli.rs'
      - 'doctave.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
      - name: 'Build manual pages'
      - with:
        toolchain: stable
      - uses: docker://pandoc/core:2.9
      - run: bash release.sh
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions-rs/toolchain@v1
      - name: 'Deploys documentation'
      - run: cargo install --git https://github.com/Doctave/doctave --tag 0.4.2
      - run: doctave build --release --allow-failed-checks
      - name: 'GitHub Pages'
      - if: github.ref == 'refs/heads/master'
      - uses: crazy-max/ghaction-github-pages@v3.0.0
      - with:
        build_dir: site/
      - env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
