name: Publish Release
on:
  push:
    branches:
      - master
    tags:
      - v*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        if: github.actor != 'dependabot[bot]'
      - id: 'compile'
        uses: rhysnewell/rust-cargo-musl-action@v0.1.14
        with:
          command: 'build'
          flags: '--features vendored-openssl'
      - uses: actions/upload-artifact@v2
        with:
          name: binary
          path: ${{ steps.compile.outputs.release-dir }}/binary
      - name: Create a Release
        if: github.actor != 'dependabot[bot]'
        uses: elgohr/Github-Release-Action@master
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          args: ${{ github.sha }}
