name: Publish Release
on:
  push:
    tags:
      - v*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
        if: github.actor != 'dependabot[bot]'
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - id: 'compile'
        uses: rhysnewell/rust-cargo-musl-action@v0.1.20
        with:
          command: 'build'
          flags: '--features vendored-openssl'
      - name: Package binaries
        run: mkdir -p release/ && cp ${{ steps.compile.outputs.release-dir }}/lorikeet INSTALL.md release/
      - name: Compress action step
        uses: master-atul/tar-action@v1.0.2
        id: compress
        with:
          command: c
          cwd: ./
          files: |
            ./release/
          outPath: lorikeet-x86_64-unknown-linux-musl-${{ env.RELEASE_VERSION }}.tar.gz
      - uses: actions/upload-artifact@v2
        with:
          name: binary
          path: lorikeet-x86_64-unknown-linux-musl-${{ env.RELEASE_VERSION }}.tar.gz
      - name: Create a Release
        if: github.actor != 'dependabot[bot]'
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          automatic_release_tag: "${{ env.RELEASE_VERSION }}"
          title: "${{ env.RELEASE_VERSION }}"
          files: |
            lorikeet-x86_64-unknown-linux-musl-${{ env.RELEASE_VERSION }}.tar.gz
